// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApxXx_j2PkUIp528T96da7jSPzl-4HHWw',
    appId: '1:405579995855:web:d33c906bd125250335b5ba',
    messagingSenderId: '405579995855',
    projectId: 'hbpostdmanagement',
    authDomain: 'hbpostdmanagement.firebaseapp.com',
    storageBucket: 'hbpostdmanagement.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsiFdSWmLxZRindtQZNtUPHaNgZIqcjDM',
    appId: '1:405579995855:android:d1562be1dafc382e35b5ba',
    messagingSenderId: '405579995855',
    projectId: 'hbpostdmanagement',
    storageBucket: 'hbpostdmanagement.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApxXx_j2PkUIp528T96da7jSPzl-4HHWw',
    appId: '1:405579995855:web:425f0e80c38c70da35b5ba',
    messagingSenderId: '405579995855',
    projectId: 'hbpostdmanagement',
    authDomain: 'hbpostdmanagement.firebaseapp.com',
    storageBucket: 'hbpostdmanagement.firebasestorage.app',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoLKl1NHlqeJbCfS7Fd0o5kQXzr32WdCI',
    appId: '1:405579995855:ios:2181849830c4598d35b5ba',
    messagingSenderId: '405579995855',
    projectId: 'hbpostdmanagement',
    storageBucket: 'hbpostdmanagement.firebasestorage.app',
    iosBundleId: 'elriztechnology.com.flutterPos',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoLKl1NHlqeJbCfS7Fd0o5kQXzr32WdCI',
    appId: '1:405579995855:ios:2181849830c4598d35b5ba',
    messagingSenderId: '405579995855',
    projectId: 'hbpostdmanagement',
    storageBucket: 'hbpostdmanagement.firebasestorage.app',
    iosBundleId: 'elriztechnology.com.flutterPos',
  );
}
