name: Flutter Build APK

on:
  push:
    branches: [ master ] 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 

      - name: Set up Java
        uses: actions/setup-java@v4 
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true 
          cache-key: v5-${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}

      - name: Clean
        run: |
          flutter clean
          rm -rf .dart_tool

      - name: Install dependencies
        run: flutter pub get

      
      - name: Build APK
<<<<<<< HEAD
        run: flutter build apk --release
=======
        run: flutter build apk --debug
>>>>>>> f6131041aaf183bf210bc730685119e260767cad

      - name: Upload APK
        uses: actions/upload-artifact@v4 
        with:
<<<<<<< HEAD
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
=======
          name: debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
>>>>>>> f6131041aaf183bf210bc730685119e260767cad
